name: pruebas_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: mostrar texto
      run: echo "Hola, esta es una prueba de CI"
    - name: mostrar fecha
      run: date